name: Bug report
description: Report a repository bug in tooling, workflows, or validation rules.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Use this form for build/validation/workflow defects.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the bug and expected behavior.
      placeholder: "Validator fails on a valid doc..."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: Provide exact commands and file paths.
      placeholder: |
        1. Run `make validate`
        2. Observe error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/output
      description: Paste relevant command output.
      render: shell
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS + Python version.
      placeholder: "macOS 14, Python 3.11"
