name: Documentation change request
description: Propose changes to corpus source docs.
title: "[Docs]: "
labels:
  - documentation
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this doc change solve?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: List doc IDs/paths affected and what changes are expected.
      placeholder: |
        - docs/software-development/api/versioning.md (swd.api.versioning.001)
        - Add migration matrix details
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Define what makes this complete.
      placeholder: "Updated doc with accurate constraints and examples."
    validations:
      required: true
